title: Amro Ahmed Eleishy
description: Senior Network Security Engineer | Firewall, SD-WAN, Cloud & Enterprise Networking
url: https://amralaishy.github.io
theme: minima

header_pages:
  - _pages/skills.md
  - _pages/experience.md
  - _pages/certifications.md
