title: Amro Eleishy
description: Senior Network Engineer â€“ Skills, Certifications & Experience
baseurl: ""
url: "https://amralaishy.github.io"

theme: minima

header_pages:
  - skills.md
  - certifications.md
  - experience.md
