
title: Amro Ahmed Eleishy
description: Senior Network Security Engineer | Firewall, SD-WAN, Cloud & Enterprise Networking
baseurl: ""
url: "https://amralaishy.github.io"

theme: minima

header_pages:
  - skills.md
  - certifications.md
  - experience.md
``
